// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template const_set_serializer.java
// Do not modify

package org.projectfloodlight.openflow.protocol.ver13;

import org.projectfloodlight.openflow.protocol.*;
import org.projectfloodlight.openflow.protocol.action.*;
import org.projectfloodlight.openflow.protocol.actionid.*;
import org.projectfloodlight.openflow.protocol.bsntlv.*;
import org.projectfloodlight.openflow.protocol.errormsg.*;
import org.projectfloodlight.openflow.protocol.meterband.*;
import org.projectfloodlight.openflow.protocol.instruction.*;
import org.projectfloodlight.openflow.protocol.instructionid.*;
import org.projectfloodlight.openflow.protocol.match.*;
import org.projectfloodlight.openflow.protocol.oxm.*;
import org.projectfloodlight.openflow.protocol.queueprop.*;
import org.projectfloodlight.openflow.types.*;
import org.projectfloodlight.openflow.util.*;
import org.projectfloodlight.openflow.exceptions.*;
import org.projectfloodlight.openflow.protocol.OFCalientOpticalPortOperState;
import java.util.Set;
import org.jboss.netty.buffer.ChannelBuffer;
import com.google.common.hash.PrimitiveSink;
import java.util.EnumSet;
import java.util.Collections;


public class OFCalientOpticalPortOperStateSerializerVer13 {

    public final static byte IN_SERVICE_VAL = (byte) 0x8;
    public final static byte OUT_OF_SERVICE_VAL = (byte) 0x10;

    public static Set<OFCalientOpticalPortOperState> readFrom(ChannelBuffer bb) throws OFParseError {
        try {
            return ofWireValue(bb.readByte());
        } catch (IllegalArgumentException e) {
            throw new OFParseError(e);
        }
    }

    public static void writeTo(ChannelBuffer bb, Set<OFCalientOpticalPortOperState> set) {
        bb.writeByte(toWireValue(set));
    }

    public static void putTo(Set<OFCalientOpticalPortOperState> set, PrimitiveSink sink) {
        sink.putByte(toWireValue(set));
    }


    public static Set<OFCalientOpticalPortOperState> ofWireValue(byte val) {
        EnumSet<OFCalientOpticalPortOperState> set = EnumSet.noneOf(OFCalientOpticalPortOperState.class);

        if((val & IN_SERVICE_VAL) != 0)
            set.add(OFCalientOpticalPortOperState.IN_SERVICE);
        if((val & OUT_OF_SERVICE_VAL) != 0)
            set.add(OFCalientOpticalPortOperState.OUT_OF_SERVICE);
        return Collections.unmodifiableSet(set);
    }

    public static byte toWireValue(Set<OFCalientOpticalPortOperState> set) {
        byte wireValue = 0;

        for(OFCalientOpticalPortOperState e: set) {
            switch(e) {
                case IN_SERVICE:
                    wireValue |= IN_SERVICE_VAL;
                    break;
                case OUT_OF_SERVICE:
                    wireValue |= OUT_OF_SERVICE_VAL;
                    break;
                default:
                    throw new IllegalArgumentException("Illegal enum value for type OFCalientOpticalPortOperState in version 1.3: " + e);
            }
        }
        return wireValue;
    }

}
