// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template of_interface.java
// Do not modify

package org.projectfloodlight.openflow.protocol;

import org.projectfloodlight.openflow.protocol.*;
import org.projectfloodlight.openflow.protocol.action.*;
import org.projectfloodlight.openflow.protocol.actionid.*;
import org.projectfloodlight.openflow.protocol.bsntlv.*;
import org.projectfloodlight.openflow.protocol.errormsg.*;
import org.projectfloodlight.openflow.protocol.meterband.*;
import org.projectfloodlight.openflow.protocol.instruction.*;
import org.projectfloodlight.openflow.protocol.instructionid.*;
import org.projectfloodlight.openflow.protocol.match.*;
import org.projectfloodlight.openflow.protocol.oxm.*;
import org.projectfloodlight.openflow.protocol.queueprop.*;
import org.projectfloodlight.openflow.types.*;
import org.projectfloodlight.openflow.util.*;
import org.projectfloodlight.openflow.exceptions.*;
import java.util.Set;
import org.jboss.netty.buffer.ChannelBuffer;

public interface OFCalientFlowStatsEntry extends OFObject {
    TableId getTableId();
    long getDurationSec();
    long getDurationNsec();
    int getPriority();
    int getIdleTimeout();
    int getHardTimeout();
    Set<OFFlowModFlags> getFlags();
    U64 getCookie();
    Set<OFCalientCflowAdminState> getAdminStatus();
    Set<OFCalientCflowOperationalState> getOperStatus();
    Set<OFCalientCflowCapability> getOperCapability();
    Set<OFCalientOcsAlarm> getAlarm();
    String getPortPower();
    String getConnectedPortPower();
    String getCflowName();
    Match getMatch();
    OFVersion getVersion();


    void writeTo(ChannelBuffer channelBuffer);

    Builder createBuilder();
    public interface Builder  {
        OFCalientFlowStatsEntry build();
        TableId getTableId();
        Builder setTableId(TableId tableId);
        long getDurationSec();
        Builder setDurationSec(long durationSec);
        long getDurationNsec();
        Builder setDurationNsec(long durationNsec);
        int getPriority();
        Builder setPriority(int priority);
        int getIdleTimeout();
        Builder setIdleTimeout(int idleTimeout);
        int getHardTimeout();
        Builder setHardTimeout(int hardTimeout);
        Set<OFFlowModFlags> getFlags();
        Builder setFlags(Set<OFFlowModFlags> flags);
        U64 getCookie();
        Builder setCookie(U64 cookie);
        Set<OFCalientCflowAdminState> getAdminStatus();
        Builder setAdminStatus(Set<OFCalientCflowAdminState> adminStatus);
        Set<OFCalientCflowOperationalState> getOperStatus();
        Builder setOperStatus(Set<OFCalientCflowOperationalState> operStatus);
        Set<OFCalientCflowCapability> getOperCapability();
        Builder setOperCapability(Set<OFCalientCflowCapability> operCapability);
        Set<OFCalientOcsAlarm> getAlarm();
        Builder setAlarm(Set<OFCalientOcsAlarm> alarm);
        String getPortPower();
        Builder setPortPower(String portPower);
        String getConnectedPortPower();
        Builder setConnectedPortPower(String connectedPortPower);
        String getCflowName();
        Builder setCflowName(String cflowName);
        Match getMatch();
        Builder setMatch(Match match);
        OFVersion getVersion();
    }
}
